[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Communication For Success - Speaking"

[build]
build-dir = "output"
create-missing = true
use-default-preprocessors = false
